services:
  db:
    image: postgres:14
    container_name: postgres_kimimi
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kimimi
      POSTGRES_PASSWORD: kimimi2506
      POSTGRES_DB: kimimi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
