"""Update models to match ER diagram

Revision ID: 1dc9507c3048
Revises: 580edda3090c
Create Date: 2025-07-17 10:00:19.737486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dc9507c3048'
down_revision: Union[str, Sequence[str], None] = '580edda3090c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('report_date', sa.Date(), nullable=False, comment='報告日'))
    op.add_column('daily_reports', sa.Column('learned_today', sa.Text(), nullable=False, comment='今日学んだこと'))
    op.add_column('daily_reports', sa.Column('learning_improvement', sa.Text(), nullable=False, comment='今日の学びの改善点'))
    op.add_column('daily_reports', sa.Column('challenge_for_tomorrow', sa.Text(), nullable=False, comment='明日チャレンジすること'))
    op.add_column('daily_reports', sa.Column('impressions', sa.Text(), nullable=False, comment='ひとこと(感想)'))
    op.add_column('daily_reports', sa.Column('other_notes', sa.Text(), nullable=True, comment='その他（任意）'))
    op.add_column('daily_reports', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'))
    op.alter_column('daily_reports', 'id',
               existing_type=sa.INTEGER(),
               comment='日報ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('daily_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_reports', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='報告者のユーザーID')
    op.drop_index(op.f('ix_daily_reports_title'), table_name='daily_reports')
    op.drop_column('daily_reports', 'content')
    op.drop_column('daily_reports', 'title')
    op.add_column('users', sa.Column('name', sa.String(), nullable=True, comment='ユーザー名'))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新日時'))
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(),
               comment='Firebase UID',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='メールアドレス',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='メールアドレス',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Firebase UID',
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'name')
    op.add_column('daily_reports', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('daily_reports', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_daily_reports_title'), 'daily_reports', ['title'], unique=False)
    op.alter_column('daily_reports', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='報告者のユーザーID')
    op.alter_column('daily_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_reports', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='日報ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('daily_reports', 'updated_at')
    op.drop_column('daily_reports', 'other_notes')
    op.drop_column('daily_reports', 'impressions')
    op.drop_column('daily_reports', 'challenge_for_tomorrow')
    op.drop_column('daily_reports', 'learning_improvement')
    op.drop_column('daily_reports', 'learned_today')
    op.drop_column('daily_reports', 'report_date')
    # ### end Alembic commands ###
